mrs_uav_managers:
  diagnostics_manager:
    main_timer_rate: 10.0 # [Hz]
    state_timer_rate: 100.0 # [Hz]
    error_publisher_rate: 2.0 # [Hz]
    host_info_rate: 1.0 # [Hz]
    node_cpu_discovery_period: 5.0 # [s]
    not_reporting_delay: 3.0 # [s]

    sensor_handlers:
      # the rate at which the sensor handlers will be updated, this is the rate at which the diagnostics will be published
      update_timer_rate: 1.0 # [Hz]
      # the list of sensors to monitor
      sensor_handler_names: [
          # Example sensor handlers
          "PX4",
          "Rangefinder",
          "GNSS",
          "Magnetometer",
          "RemoteController",
          # "SimulationCamera"
          # "LidarHandler",
          # "IMUHandler",
          # "BatteryHandler",
          # "RangeFinderHandler",
        ]

      # ExampleHandler:
      # type: "Example" # Example, Autopilot, Camera, Lidar, IMU, GNSS, Battery, Barometer, Magnetometer, RangeFinder
      # address: "mrs_robot_diagnostics/ExampleHandler"
      # topic: "example_node/topic" # Don't add the leading slash, the name will be resolved relative to the node's namespace
      # expected_publisher:
      #   node: "example_node" # Name of the node expected to publish the topic (optional, used for more specific diagnostics)
      #   component: "example_component" # Name of the component within the node expected to publish the topic (optional)
      # message_type: "std_msgs/msg/String"
      # qos_reliability: "reliable"              # QoS reliability setting (default: "reliable")
      # expected_rate: 10.0                      # Hz
      # rate_tolerance: 0.3                      # 30% deviation allowed (default)

      # define "running" instances of plugins, there can be multiple instances of the same plugin
      SimulationCamera:
        type: "Camera"
        address: "mrs_robot_diagnostics/CameraSensorHandler"
        topic: "servo_camera/camera_info"
        message_type: "sensor_msgs/msg/CameraInfo"
        qos_reliability: "reliable"
        expected_rate: 60.0
        rate_tolerance: 0.3

      # Using generic handler
      PX4:
        type: "Autopilot"
        address: "mrs_robot_diagnostics/GenericSensorHandler"
        topic: "hw_api/status"
        message_type: "mrs_msgs/msg/HwApiStatus"
        qos_reliability: "reliable"
        expected_rate: 100.0
        rate_tolerance: 0.3

      Rangefinder:
        type: "Rangefinder"
        address: "mrs_robot_diagnostics/GenericSensorHandler"
        topic: "hw_api/distance_sensor"
        message_type: "sensor_msgs/msg/Range"
        qos_reliability: "reliable"
        expected_rate: 100.0
        rate_tolerance: 0.3

      GNSS:
        type: "GNSS"
        address: "mrs_robot_diagnostics/GNSSSensorHandler"
        topic: "hw_api/gnss"
        status_topic: "hw_api/gnss_status"
        qos_reliability: "reliable"
        expected_rate: 50.0
        rate_tolerance: 0.3

      Magnetometer:
        type: "Magnetometer"
        address: "mrs_robot_diagnostics/MagnetometerSensorHandler"
        topic: "hw_api/magnetic_field"
        qos_reliability: "reliable"
        expected_rate: 15.0
        rate_tolerance: 0.3

      RemoteController:
        type: "RemoteController"
        address: "mrs_robot_diagnostics/RCSensorHandler"
        topic: "hw_api/rc_rssi"
        qos_reliability: "reliable"
        expected_rate: 10.0
        rate_tolerance: 0.3
