mrs_uav_managers:

  gain_manager:

    estimator_types: [
      "gps_garmin",
      "gps_baro",
      "rtk",
      "rtk_garmin",
      "other",
      "ground_truth",
      "passthrough",
      "f9p",
      "dummy",
    ]

    gains: [
      "supersoft",
      "soft",
    ]

    # list of allowed gains per odometry mode
    allowed_gains:
      gps_garmin: ["supersoft", "soft"]
      gps_baro: ["supersoft", "soft"]
      rtk: ["supersoft", "soft"]
      rtk_garmin: ["supersoft", "soft"]
      other: ["supersoft", "soft"]
      ground_truth: ["supersoft", "soft"]
      passthrough: ["supersoft", "soft"]
      f9p: ["supersoft", "soft"]
      dummy: ["supersoft"]

    # those gains will be used automatically when a localization mode switches
    # and the current gains are not in the allowed list (next paragraphs)
    default_gains:
      gps_garmin: "soft"
      gps_baro: "soft"
      rtk: "soft"
      rtk_garmin: "soft"
      other: "supersoft"
      ground_truth: "soft"
      passthrough: "soft"
      f9p: "soft"
      dummy: "supersoft"
