mrs_uav_managers:

  estimation_manager:

    debug_topics:
      input: true
      output: true
      state: true
      covariance: false
      innovation: false
      correction: true
      correction_delay: false
      diagnostics: false
