MpcTracker:
  address: "mrs_uav_trackers/MpcTracker"
  human_switchable: true

LandoffTracker:
  address: "mrs_uav_trackers/LandoffTracker"

LineTracker:
  address: "mrs_uav_trackers/LineTracker"

JoyTracker:
  address: "mrs_uav_trackers/JoyTracker"

MatlabTracker:
  address: "mrs_uav_trackers/MatlabTracker"

SpeedTracker:
  address: "mrs_uav_trackers/SpeedTracker"

FlipTracker:
  address: "mrs_uav_trackers/FlipTracker"

MidairActivationTracker:
  address: "mrs_uav_trackers/MidairActivationTracker"

NullTracker:
  address: "mrs_uav_managers/NullTracker"
