takeoff:

  during_takeoff:
    tracker: "LandoffTracker"
    controller: "MpcController"

  after_takeoff:
    tracker: "MpcTracker"
    controller: "Se3Controller"

    pirouette: false

  takeoff_height: 1.5

landing:

  disarm: false
