mrs_uav_managers:

  estimation_manager:

    gps_garmin:
      address: "mrs_uav_state_estimators/GpsGarmin"
    gps_baro:
      address: "mrs_uav_state_estimators/GpsBaro"
    rtk:
      address: "mrs_uav_state_estimators/Rtk"
    aloam:
      address: "mrs_uav_state_estimators/Aloam"
    vio:
      address: "mrs_uav_state_estimators/Vio"
    hector_garmin:
      address: "mrs_uav_state_estimators/HectorGarmin"
    passthrough:
      address: "mrs_uav_state_estimators/Passthrough"
    ground_truth:
      address: "mrs_uav_state_estimators/GroundTruth"
    dummy:
      address: "mrs_uav_state_estimators/Dummy"
    garmin_agl:
      address: "mrs_uav_state_estimators/GarminAgl"
