mrs_uav_managers:

  uav_manager:

    # require gain or constraint manager running to takeoff?
    require_gain_manager: true
    require_constraint_manager: true

    # periodically checks if max height was exceeded
    # if so, retakes control and descends below it
    max_height_checking:

      enabled: true
      rate: 10.0 # [Hz]
      safety_height_offset: 0.25 # how much lower to descend below the max height

    # periodically checks if min height was exceeded
    # if so, retakes control and ascends above it
    min_height_checking:

      enabled: true
      rate: 10.0 # [Hz]
      min_height: 0.5 # [m]
      safety_height_offset: 0.25 # how much higher to ascend above the min height

    takeoff:

      rate: 10 # [Hz]

      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "MpcController"
        tracker: "MpcTracker"

      takeoff_height: 1.5

    landing:

      rate: 10 # [Hz]
      landing_tracker: "LandoffTracker"
      landing_controller: "MpcController"

      # those two must apply simultaneously
      landing_cutoff_mass_factor:  0.5 # how much lighter does the drone appear to be?
      landing_cutoff_timeout:  2.0 # [s] how long does the throttle has to be below the mass factor

      disarm: true

      # if the height estimate is available, and
      # if the UAV higher than this height:
      # the UAV will first descend to this height using a goto command,
      # and then land slowly using the landing tracker and controller
      descend_height: 2.0 # [m]

      tracking_tolerance:
        translation: 0.1 # [m]
        heading: 0.1 # [rad]

    midair_activation:

      after_activation:
        controller: "MpcController"
        tracker: "MpcTracker"

    flight_timer:

      enabled: false
      rate: 1 # [Hz]
      max_time: 10 # [s]

    # detecting if desired throttle cross max threshold, triggers landing after that
    max_throttle:

      enabled: true
      rate: 30 # [Hz]
      max_throttle: 0.80 # [-]
      eland_timeout: 1.0 # [s]
      ungrip_timeout: 0.5 # [s]
