mrs_uav_managers:
  diagnostics_manager:
    sensor_handlers:
      # pluginlib class addresses for the "running" instances defined in the public config
      SimulationCamera:
        address: "mrs_uav_diagnostics_sensors/CameraSensorHandler"

      PX4:
        address: "mrs_uav_diagnostics_sensors/GenericSensorHandler"

      Rangefinder:
        address: "mrs_uav_diagnostics_sensors/GenericSensorHandler"

      GNSS:
        address: "mrs_uav_diagnostics_sensors/GNSSSensorHandler"

      Magnetometer:
        address: "mrs_uav_diagnostics_sensors/MagnetometerSensorHandler"

      RemoteController:
        address: "mrs_uav_diagnostics_sensors/RCSensorHandler"
