mrs_uav_managers:

  estimation_manager:

    gps_garmin:
      address: "mrs_uav_state_estimators::gps_garmin::GpsGarmin"
    gps_baro:
      address: "mrs_uav_state_estimators::gps_baro::GpsBaro"
    rtk:
      address: "mrs_uav_state_estimators::rtk::Rtk"
    rtk_garmin:
      address: "mrs_uav_state_estimators::rtk_garmin::RtkGarmin"
    passthrough:
      address: "mrs_uav_state_estimators::passthrough::Passthrough"
    f9p:
      address: "mrs_uav_state_estimators::f9p::F9P"
    ground_truth:
      address: "mrs_uav_state_estimators::ground_truth::GroundTruth"
    dummy:
      address: "mrs_uav_state_estimators::dummy::Dummy"
    garmin_agl:
      address: "mrs_uav_state_estimators::garmin_agl::GarminAgl"
