mrs_uav_managers:

  estimation_manager:

    gps_garmin:
      address: "mrs_uav_state_estimators/GpsGarmin"
    gps_baro:
      address: "mrs_uav_state_estimators/GpsBaro"
    rtk:
      address: "mrs_uav_state_estimators/Rtk"
    rtk_garmin:
      address: "mrs_uav_state_estimators/RtkGarmin"
    passthrough:
      address: "mrs_uav_state_estimators/Passthrough"
    f9p:
      address: "mrs_uav_state_estimators/F9P"
    ground_truth:
      address: "mrs_uav_state_estimators/GroundTruth"
    dummy:
      address: "mrs_uav_state_estimators/Dummy"
    garmin_agl:
      address: "mrs_uav_state_estimators/GarminAgl"
